#pragma config(Sensor, S1,     Rcolor,         sensorI2CCustom)
#pragma config(Sensor, S2,     Lcolor,         sensorI2CCustom)
#pragma config(Sensor, S3,     RBsensor,       sensorEV3_Color)
#pragma config(Sensor, S4,     LBsensor,       sensorEV3_Color)
#pragma config(Motor,  motorA,          UpArm,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Lmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Rmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          CaArm,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  motorD,          Flontmotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Users\joho\Desktop\mellcover\drivers\hitechnic-colour-v1.h"

#define black 40
#define kakudo 26
#define R 252


void opentest(void);
void Ready(void);
void trace(int x);
void ST(float x,int PW);
void RT(float R1,int PW);
void LT(float R1,int PW);
void usetu(float R1,int PW);
void sasetu(float R1,int PW);
void get(int n);
void kakuno(int m);
void awase(float z,int P,float R3);
void color(int x);
void BaseIN(int x);
void ReadT(int n);
void last(void);
void MV(int PW);
void hyouzi(void);
void RST(void);
void AS(void);
void MotorMode(int x);
void colorsound(int x);
void goal(void);
void STOPF(int PW);
void STOPB(int PW);
int TB(void);
int blue(int color);
int kuro(int color);
int green(int color);
int yellow(int color);
int red(int color);
int white(int color);


int s_hitec(tSensors port){
	static int red,green,blue;
	HTCSreadRGB(port,red,green,blue);
	return((red+green+blue)/3);
}

float GEIN=0.1;
int static Mode=0;
int static FPOWER=-17;
int static X=1;
int static Y;
int static BF=0;
int static RED=0;
int static s;
int static T=0;
int static SA=14;
int DC[3]={11,11,11};
int BC[3]={4,9,0};
int g[4]={2,4,6,8};
int fin=0;

task main(){
	int n=0;
	while(1){
	RT(R,50);
	}
	RST();
	Ready();
	RST();
	X=0;
	if(n==0) ST(360,100);
	waitUntilMotorStop(Rmotor);
	while(1&&fin==0){
		X=0;
		if(Mode==1) MV(FPOWER);
		else trace(SA);
		if(s_hitec(S1)<=black&&s_hitec(S2)<=black||(getColorReflected(S3)<12&&Mode==1)){
			X=1;
			playImmediateTone(400,30);
			get(n);
			n++;
			hyouzi();
		}
	}
}

void get(int n){
	RST();
	if(n==0){
		ST(28,100);
		usetu(R*3,100);
	}
	if(n==1){
		kakuno(0);
		X=0;
		ST(140,100);
		sleep(100);
		moveMotorTarget(UpArm,500,-100);
		sleep(500);
		X=1;
		LT(R/2,100);
		Mode=1;
	}
	if(n==2){
		Mode=0;
		ST(130,100);
		RT(R,100);
		AS();
	}
	if(n==3){
		kakuno(1);
		RST();
		moveMotorTarget(CaArm,500,100);
		waitUntilMotorStop(CaArm);
		RST();
		moveMotorTarget(UpArm,150,-100);
		sleep(400);
		moveMotorTarget(CaArm,400,-100);
		sleep(300);
		X=0;
		LT(R*2,100);
		waitUntilMotorStop(Rmotor);
		RST();
		moveMotorTarget(CaArm,200,100);
		sleep(300);
		MV(40);
		sleep(300);
		moveMotorTarget(CaArm,600,-100);
		sleep(300);
		moveMotorTarget(UpArm,500,-100);
		while(getColorReflected(S4)>40) sleep(10);
		RST();
		X=1;
		RT(R/2,30);
		ST(380,100);
		sleep(500);
		Mode=1;
	}
	if(n==4){
		Mode=0;
		ST(130,100);
		RT(R,100);
		AS();
	}
	if(n==5){
		kakuno(2);
		RST();
		moveMotorTarget(CaArm,400,100);
		sleep(300);
		X=0;
		ST(200,20);
		sleep(400);
		moveMotorTarget(UpArm,400,-100);
		sleep(200);
		moveMotorTarget(CaArm,500,-100);
		//waitUntilMotorStop(Rmotor);
		sleep(700);
		X=1;
		RST();
		ST(620,-100);
		LT(R,50);
		AS();
		int c=0;
		FPOWER=25;
		while(c<90){
			trace(SA);
			c++;
		}
		moveMotorTarget(UpArm,100,100);
		sleep(300);
		FPOWER=15;
		SA=2;
	}
	if(n==6){
		SA=14;
		FPOWER=20;
		X=0;
		ST(580,30);
		moveMotorTarget(CaArm,600,100);
		sleep(200);
		moveMotorTarget(UpArm,300,-100);
		sleep(100);
		waitUntilMotorStop(Rmotor);
		RST();
		//int a=0;
		X=1;
		usetu(R,30);
		ST(50,30);
		STOPF(30);
		X=0;
		ST(150,30);
		moveMotorTarget(CaArm,600,-100);
		moveMotorTarget(UpArm,50,100);
		waitUntilMotorStop(Rmotor);
		X=1;
		LT(R,30);
		/*awase(28,20,0);

		RST();
		X=0;
		while(a==0){
		MV(15);
		if(s_hitec(S1)<=black&&s_hitec(S2)<=black){
		a=1;
		}
		}*/
		moveMotorTarget(CaArm,600,100);
		STOPF(20);
		int x;
		for(x=0;x<=2;x++){
			playImmediateTone(220,30);
			if(BC[x]>=1&&BC[x]<=3) g[0]=0;
			if(BC[x]==0) g[1]=0;
			if(BC[x]==4) g[2]=0;
			if(BC[x]==5||BC[x]==6) g[3]=0;
		}
		ST(150,30);
		moveMotorTarget(CaArm,200,-100);
		sleep(500);
		for(x=0;x<=3;x++){
			if(g[x]!=0){
				BF=g[x]-1;
				s=BF;
				if(g[x]>4){
					g[x]=8-g[x];
					LT(g[x]*R/2,30);
				}
				else RT(g[x]*R/2,30);
				break;
			}
		}
		int r;
		for(r=0;r<3;r++) if(red(BC[r])) RED=1;
		if(RED==0) ST(450,50);
		else ST(200,50);
		RST();
		moveMotorTarget(CaArm,250,100);
		sleep(200);
		moveMotorTarget(UpArm,20,100);
		sleep(300);
		if(BC[2]>=7&&BC[2]<=10) ST(122,-50);
		else ST(45,-50);
		moveMotorTarget(CaArm,400,-100);
		sleep(500);
		if(BC[2]>=7&&BC[2]<=10) ST(312,-100);
		else if(RED==0) ST(627,-100);
		else ST(377,-100);
		RST();
		moveMotorTarget(CaArm,400,100);
		sleep(300);
		STOPF(40);
		X=0;
		ST(144,40);
		sleep(100);
		moveMotorTarget(CaArm,600,-100);
		waitUntilMotorStop(Rmotor);
		X=1;
		moveMotorTarget(UpArm,100,-100);
		sleep(300);
		color(2);
		ReadT(0);
		if(Y!=0) BaseIN(0);
		color(1);
		ReadT(1);
		if(Y!=0) BaseIN(1);
		color(0);
		ReadT(2);
		if(Y!=0) BaseIN(2);
		last();
	}
	if(n==7){
		//int b=0;
		//b=TB();
		Mode=0;
		X=0;//Ready
		moveMotorTarget(CaArm,600,100);
		ST(250,-50);
		waitUntilMotorStop(Rmotor);
		X=1;
		int a=0;
		while(a==0){
			MV(-30);
			if(getColorReflected(S3)<30) a=1;
		}
		ST(151.2,-50);
		FPOWER=30;
		RT(R,30);
		while(a==1){
			MV(30);
			if(getColorReflected(S4)<30) a=0;
		}
		ST(100,30);
		usetu(R,50);
		sasetu(R*3,50);
		AS();
		ST(144,30);
		while(1){
			MV(30);
			if(getColorReflected(S4)<30) break;
		}
		moveMotorTarget(UpArm,400,100);
		while(1){
			MV(-30);
			if(getColorReflected(S4)<30) break;
		}
		X=1;
		ST(151.2,-30);
		LT(R,100);
		ST(400,100);
		usetu(R,100);
		ST(300,100);
		X=0;
		ST(300,-100);
		moveMotorTarget(CaArm,600,-100);
		sleep(500);
		moveMotorTarget(UpArm,260,-100);
		waitUntilMotorStop(Rmotor);
		usetu(R,-100);
		waitUntilMotorStop(Lmotor);
		int c=0;
		while(c<45){
			trace(SA);
			c++;
		}
		goal();
	}
	if(n==9){}
	if(n==100){
		BaseIN(0);
	}
}

void opentest(void){
	int sa;
	eraseDisplay();
	while(1 != getButtonPress(buttonEnter)){
		sa=s_hitec(S1)-s_hitec(S2);
		displayBigTextLine(0, "OpenTest");
		displayTextLine(3, "LSENSER:%d ", s_hitec(S1));
		displayTextLine(4, "RSENSER:%d ", s_hitec(S2));
		displayTextLine(5, "RSENSERColor:%d ", HTCSreadColor(S1));
		displayTextLine(6, "RSENSERColor:%d ", HTCSreadColor(S2));
		displayTextLine(7, "RBSENSER:%d ", getColorReflected(S3));
		displayTextLine(8, "LBSENSER:%d ", getColorReflected(S4));
		displayTextLine(9, "sa:%d ", sa);
	}
	eraseDisplay();
}

void Ready(void){
	moveMotorTarget(CaArm,600,-100);
	moveMotorTarget(UpArm,400,100);
	sleep(500);
}

void trace(int x){
	float sa=0;
	sa=(s_hitec(S1)-s_hitec(S2)+x)*GEIN;
	motor[Lmotor]=sa+FPOWER;
	motor[Rmotor]=-sa+FPOWER+0.5;
}

void MV(int PW){
	motor(Rmotor)=PW;
	motor(Lmotor)=PW;
}

void ST(float x,int PW){
	if(X==1&&T==0) RST();
	moveMotorTarget(Lmotor,x,PW);
	moveMotorTarget(Rmotor,x,PW);
	if(X==1) waitUntilMotorStop(Rmotor);
}

void RT(float R1,int PW){
	if(X==1&&T==0) RST();
	int RP=0;
	RP=PW;
	moveMotorTarget(Rmotor,R1,-RP-0.5);
	moveMotorTarget(Lmotor,R1,RP);
	if(X==1) waitUntilMotorStop(Rmotor);
}

void LT(float R1,int PW){
	if(X==1&&T==0) RST();
	int LP=0;
	LP=PW;
	moveMotorTarget(Rmotor,R1,LP+0.5);
	moveMotorTarget(Lmotor,R1,-LP);
	if(X==1) waitUntilMotorStop(Rmotor);
}

void usetu(float R1,int PW){
	if(X==1&&T==0) RST();
	moveMotorTarget(Rmotor,R1,0);
	moveMotorTarget(Lmotor,R1,PW);
	waitUntilMotorStop(Lmotor);
}

void sasetu(float R1,int PW){
	if(X==1&&T==0) RST();
	moveMotorTarget(Rmotor,R1,PW);
	moveMotorTarget(Lmotor,R1,0);
	waitUntilMotorStop(Rmotor);
}

void kakuno(int m){
	RST();
	int a=0,b=0;
	ST(28,100);
	usetu(R,50);
	moveMotorTarget(CaArm,600,100);
	sleep(100);
	while(a==0){
		MV(40);
		if(getColorReflected(S4)<50) a=1;
	}
	RST();
	moveMotorTarget(UpArm,300,100);
	sleep(100);
	moveMotorTarget(CaArm,600,-100);
	sleep(500);
	RST();
	moveMotorTarget(UpArm,100,-100);
	sleep(300);
	X=1;
	ST(151.2,-50);
	RST();
	RT(R,-50);
	moveMotorTarget(UpArm,220,-100);
	waitUntilMotorStop(Rmotor);
	while(a==1){
		MV(40);
		if(getColorReflected(S3)<40) a=0;
	}
	RST();
	sleep(300);
	if(HTCSreadColor(S1)>=2&&HTCSreadColor(S1)<=10) LT(10,30);
	if(HTCSreadColor(S2)>=2&&HTCSreadColor(S2)<=10)	RT(10,30);
	if(s_hitec(S1)<20) LT(10,30);
	if(s_hitec(S2)<20) RT(10,30);
	moveMotorTarget(CaArm,200,100);
	sleep(300);
	moveMotorTarget(UpArm,70,100);
	sleep(300);
	while(b==0){
		moveMotorTarget(CaArm,300,-10);
		if(HTCSreadColor(S1)>=1&&HTCSreadColor(S1)<=10||HTCSreadColor(S2)>=1&&HTCSreadColor(S2)<=10){
			playImmediateTone(220,30);
			if(HTCSreadColor(S1)>=1&&HTCSreadColor(S1)<=10) BC[m]=HTCSreadColor(S1);
			if(HTCSreadColor(S2)>=1&&HTCSreadColor(S2)<=10) BC[m]=HTCSreadColor(S2);
			b=1;
		}
		if(s_hitec(S1)<=15||s_hitec(S2)<=15){
			playImmediateTone(400,30);
			BC[m]=0;
			b=1;
		}
	}
	colorsound(BC[m]);
	moveMotorTarget(CaArm,500,-100);
	sleep(600);
}

void awase(float z,int P,float R3){
	RST();
	int a=0;
	LT(R3,30);
	while(a==0){
		X=0;
		LT(R*2,P);
		wait1Msec(1);
		if(s_hitec(S2)<=black){
			X=1;
			RT(z,30);
			a=1;
		}
	}
}

void color(int x){
	if(BC[x]>=1&&BC[x]<=3) Y=1;
	if(BC[x]==0) Y=3;
	if(BC[x]==4) Y=5;
	if(BC[x]==5||BC[x]==6) Y=7;
	if(BC[x]>=7&&BC[x]<=10) Y=10;
}

void BaseIN(int x){
	int a=0,c=0;
	AS();
	RST();
	moveMotorTarget(CaArm,300,-100);
	sleep(300);
	RST();
	FPOWER=25;
	while(c<30){
		trace(20);
		c++;
	}
	FPOWER=10;
	GEIN=0.07;
	playImmediateTone(220,30);
	moveMotorTarget(UpArm,100,100);
	while(a==0){
		if(HTCSreadColor(S1)>=2&&HTCSreadColor(S1)<=10||HTCSreadColor(S2)>=2&&HTCSreadColor(S2)<=10){
			playImmediateTone(220,30);
			a=1;
		}
		if((s_hitec(S1)<=20)||(s_hitec(S2)<=20)){
			playImmediateTone(220,30);
			a=1;
		}
		trace(5);
	}
	GEIN=0.1;
	RST();
	playImmediateTone(400,50);
	moveMotorTarget(CaArm,350,100);
	sleep(500);
	X=0;
	RST();
	ST(56.8+x*80.64,-20);
	sleep(100);
	moveMotorTarget(UpArm,160,-100);
	waitUntilMotorStop(Rmotor);
	RST();
	moveMotorTarget(CaArm,150,-100);
	ST(130+x*80.64,20);
	waitUntilMotorStop(Rmotor);
	X=1;
	moveMotorTarget(CaArm,600,100);
	sleep(500);
	ST(55,20);
	moveMotorTarget(UpArm,200,-100);
	sleep(200);
	moveMotorTarget(CaArm,200,-100);
	sleep(200);
	RST();
	moveMotorTarget(UpArm,320,100);
	sleep(500);
	X=0;
	ST(130,-15);
	sleep(650);
	moveMotorTarget(CaArm,200,100);
	waitUntilMotorStop(Rmotor);
	X=1;
	if(x==0){
		ST(35,-100);
		moveMotorTarget(UpArm,400,-100);
		sleep(500);
		moveMotorTarget(CaArm,400,-100);
		sleep(400);
		ST(100,-30);
		moveMotorTarget(CaArm,200,100);
		sleep(100);
		moveMotorTarget(UpArm,450,100);
		sleep(700);
		X=0;
		ST(170,40);
		moveMotorTarget(CaArm,600,-100);
		waitUntilMotorStop(Rmotor);
		RST();
		ST(50,-20);
		moveMotorTarget(UpArm,250,-30);
		sleep(700);
		X=1;
	}
	if(x!=0){
		ST(20,-100);
		moveMotorTarget(CaArm,700,-100);
		moveMotorTarget(UpArm,180,-100);
		sleep(500);
	}
	a=0;
	ST(144,-100);
	while(a==0){
		MV(-30);
		if(getColorReflected(S3)<20) a=1;
	}
	ST(151.2,-40);
	RST();
	moveMotorTarget(UpArm,300,-100);
	sleep(200);
}

void ReadT(int n){
	if(n==3) Y=Y+2;
	int PW=100,RS;
	playImmediateTone(220,30);
	if(Y!=10){
		if(Y-BF<0){
			RS=(Y-BF)*(-1);
		}
		else RS=Y-BF;
		if(BF>Y&&RS>=4) RT((8-RS)*(R/2),PW);
		else if(BF<Y&&RS>=4) LT((8-RS)*(R/2),PW);
		else if(BF>Y)LT(RS*(R/2),PW);
		else if(BF>Y&&RS>=4) LT((8-RS)*(R/2),PW);
		else RT(RS*(R/2),PW);
	}
	else if(Y==10){
		if(n!=0){
			FPOWER=10;
			if(n==2) Y=s+2;
			else Y=s;
			if(Y-BF<0) RS=(Y-BF)*(-1);
			else RS=Y-BF;
			if(BF>Y&&RS>=4) RT((8-RS)*(R/2),PW);
			else if(BF<Y&&RS>=4) LT((8-RS)*(R/2),PW);
			else if(BF>Y)LT(RS*(R/2),PW);
			else if(BF>Y&&RS>=4) LT((8-RS)*(R/2),PW);
			else RT(RS*(R/2),PW);
			RST();
			if(n==2){
				int a=0;
				while(a==0){
					MV(20);
					if(getColorReflected(S3)<20||getColorReflected(S4)<20) a=1;
				}
				ST(151.2,-100);
				awase(28,20,R/2);
			}
			moveMotorTarget(UpArm,240,PW);
			sleep(500);
			int a=0;
			FPOWER=7;
			while(a==0){
				trace(5);
				if(HTCSreadColor(S1)>=7&&HTCSreadColor(S1)<=9||HTCSreadColor(S2)>=7&&HTCSreadColor(S2)<=9) a=1;
			}
			RST();
			moveMotorTarget(CaArm,500,PW);
			sleep(500);
			ST(56.8+n*80.64,-30);
			moveMotorTarget(UpArm,170,-PW);
			sleep(250);
			moveMotorTarget(CaArm,300,-PW);
			sleep(250);
			ST(1.8+n*80.64,20);
			moveMotorTarget(CaArm,330,PW);
			sleep(300);
			if(n==1){
				ST(70,-PW);
				moveMotorTarget(CaArm,700,-PW);
				moveMotorTarget(UpArm,500,-PW);
				sleep(500);
				ST(63,-PW);
			}
		}
		BF=s;
		Y=0;
		RED=1;
	}
	if(Y!=0) BF=Y;
}

void last(void){
	RST();
	int a=0;
	if(Y!=0){
		Y=s;
		ReadT(3);
		while(a==0){
			MV(20);
			if(getColorReflected(S3)<20||getColorReflected(S4)<20) a=1;
		}
		ST(151.2,-100);
		awase(28,20,R/2);
		a=0;
	}
	if(RED==0){
		moveMotorTarget(CaArm,600,100);
		sleep(500);
	}
	if(RED==1){
		if(Y!=0){
			AS();
			moveMotorTarget(UpArm,100,100);
			FPOWER=7;
			while(a==0){
				trace(2);
				if(HTCSreadColor(S1)>=7&&HTCSreadColor(S1)<=9||HTCSreadColor(S2)>=7&&HTCSreadColor(S2)<=9){
					a=1;
				}
			}
			RST();
			ST(40,30);
			moveMotorTarget(CaArm,600,100);
			sleep(300);
			moveMotorTarget(UpArm,100,-100);
			sleep(500);
			RST();
		}
		else moveMotorTarget(UpArm,60,100);
		sleep(300);
		RST();
		moveMotorTarget(CaArm,400,-100);
		sleep(500);
		RST();
		moveMotorTarget(CaArm,100,100);
		sleep(500);
		X=0;
		a=0;
		/*while(a==0){
		MV(12);
		if(s_hitec(S1)<100||s_hitec(S2)<100){
		RST();
		a=1;
		playImmediateTone(400,30);
		}
		}
		X=1;
		RST();
		ST(14,20);*/
		ST(55,20);
		moveMotorTarget(CaArm,400,100);
		sleep(500);
		moveMotorTarget(UpArm,100,-100);
		sleep(300);
		RST();
		moveMotorTarget(CaArm,200,-100);
		sleep(500);
		moveMotorTarget(UpArm,300,100);
		sleep(1000);
		X=0;
		ST(130,-15);
		sleep(650);
		moveMotorTarget(CaArm,200,100);
		sleep(1000);
		X=1;
		moveMotorTarget(UpArm,500,-100);
		sleep(700);
		RST();
		moveMotorTarget(UpArm,50,100);
		moveMotorTarget(CaArm,250,-100);
		sleep(500);
	}
	if(RED==1){
		//ST(90,-50);
		STOPF(-15);
		ST(160,30);
	}
	if(s==1){
		RT(R,50);
		//ST(160,-30);
		STOPF(-15);
		ST(40,-30);
		s=1;
	}
	else if(s==7){
		LT(R,50);
		//ST(160,-30);
		STOPF(-15);
		ST(40,-30);
		s=7;
	}
	else{
		//ST(160,-30);
		STOPF(-15);
		ST(40,-30);
	}//ST(220,-30);
	RST();
	moveMotorTarget(CaArm,600,100);
	moveMotorTarget(UpArm,200,100);
	sleep(500);
	ST(72,-30);
	if(s<4) LT(R,50);
	if(s>4) RT(R,50);
	moveMotorTarget(UpArm,100,-100);
	sleep(300);
	ST(80,30);
	STOPB(20);
	moveMotorTarget(CaArm,600,100);
	sleep(700);
	ST(180,30);
	STOPF(20);
	X=0;
	ST(100,15);
	sleep(100);
	moveMotorTarget(CaArm,600,-100);
	waitUntilMotorStop(Rmotor);
	X=1;
	ST(244,-50);
	if(s<4) LT(R,50);
	if(s>4) RT(R,50);
	moveMotorTarget(CaArm,600,100);
	sleep(700);
	ST(50,30);
	STOPF(20);
	X=0;
	ST(100,15);
	sleep(100);
	moveMotorTarget(CaArm,600,-100);
	waitUntilMotorStop(Rmotor);
	X=1;
	ST(280,-50);
	STOPB(-30);
	ST(151.2+288,-30);
	if(s<4) RT(R,50);
	if(s>4) LT(R,50);
	ST(576,-30);
	if(s<4) LT(R/2,50);
	if(s>4) RT(R/2,50);
	STOPF(-30);
	ST(72,-30);
	STOPB(-30);
	ST(30,-30);
	sasetu(R*2,-50);
	goal();
	/*
	moveMotorTarget(UpArm,100,100);
	ST(70,-30);
	moveMotorTarget(CaArm,600,-100);
	sleep(500);
	if(s==1){
	LT(R,30);
	ST(288,-30);
	RT(R/2,30);
	}
	else {
	RT(R,30);
	ST(288,-30);
	LT(R/2,30);
	}
	Mode=1;
	FPOWER=-20;
	*/
}

int TB(void){
	int x=0,g=0,t,b=0;
	while(g==0&&x<3){
		if(BC[x]==0){
			t=x;
			g=1;
		}
		else if(BC[x]==4){
			t=x;
			g=1;
		}
		else if(BC[x]>=7&&BC[x]<=10) t=x;
		x++;
	}
	b=blue(DC[t]);
	if(b!=0) return(b);
	b=kuro(DC[t]);
	if(b!=0) return(b);
	b=green(DC[t]);
	if(b!=0) return(b);
	b=yellow(DC[t]);
	if(b!=0) return(b);
	b=red(DC[t]);
	if(b!=0) return(b);
	return(b);
}

void goal(void){
	int a=0;
	while(a==0){
		MV(-100);
		if(green(HTCSreadColor(S1))==3||green(HTCSreadColor(S2))==3) a=1;
	}
	RST();
	ST(30,100);
	fin=1;
}

void hyouzi(void){
	displayTextLine(10,"%d%d%d",DC[0],DC[1],DC[2]);
	displayTextLine(12,"%d%d%d",BC[0],BC[1],BC[2]);
}

void RST(void){
	motor(UpArm)=0;
	motor(CaArm)=0;
	motor(Rmotor)=0;
	motor(Lmotor)=0;
	resetMotorEncoder(UpArm);
	resetMotorEncoder(CaArm);
	resetMotorEncoder(Lmotor);
	resetMotorEncoder(Rmotor);
}

void AS(void){
	if(X==1) RST();
	moveMotorTarget(UpArm,140,50);
	waitUntilMotorStop(UpArm);
}

int blue(int color){
	if(color>=1&&color<=3){
		playSoundFile("Blue");
		return(1);
	}
	return(0);
}

int kuro(int color){
	if(color==0){
		playSoundFile("Black");
		return(2);
	}
	return(0);
}

int green(int color){
	if(color==4){
		playSoundFile("Green");
		return(3);
	}
	return(0);
}

int yellow(int color){
	if(color>=5&&color<=6){
		playSoundFile("Yellow");
		return(4);
	}
	return(0);
}

int red(int color){
	if(color>=7&&color<=10){
		playSoundFile("Red");
		return(5);
	}
	return(0);
}

int white(int color){
	if(color>=11&&color<=17){
		playSoundFile("White");
		return(6);
	}
	return(0);
}

void MotorMode(int x){
	if(x==1){
		setMotorBrakeMode(Rmotor,motorCoast);//kannsei
		setMotorBrakeMode(Lmotor,motorCoast);
		T=1;
	}
	if(x==0){
		setMotorBrakeMode(Rmotor,motorBrake);//tomaru
		setMotorBrakeMode(Lmotor,motorBrake);
		T=0;
	}
}

void colorsound(int x){
	blue(x);
	kuro(x);
	green(x);
	yellow(x);
	red(x);
	white(x);
}

void STOPF(int PW){
	int STR=0,STL=0;
	while(STR==0||STL==0){
		if(s_hitec(S2)>70&&STR==0) motor(Rmotor)=PW;
		else{
			motor(Rmotor)=0;
			STR=1;
		}
		if(s_hitec(S1)>70&&STL==0) motor(Lmotor)=PW;
		else{
			motor(Lmotor)=0;
			STL=1;
		}
	}
}

void STOPB(int PW){
	int STR=0,STL=0;
	while(STR==0||STL==0){
		if(getColorReflected(S3)>30&&STR==0) motor(Rmotor)=PW;
		else{
			motor(Rmotor)=0;
			STR=1;
		}
		if(getColorReflected(S4)>30&&STL==0) motor(Lmotor)=PW;
		else{
			motor(Lmotor)=0;
			STL=1;
		}
	}
}
