#pragma config(Sensor, S1,     Rsensor,        sensorI2CCustom)
#pragma config(Sensor, S2,     Lsensor,        sensorI2CCustom)
#pragma config(Sensor, S3,     RBsensor,       sensorEV3_Color)
#pragma config(Sensor, S4,     LBsensor,       sensorEV3_Color)
#pragma config(Motor,  motorA,          up,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          Rmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Lmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          ca,            tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Users\user\Desktop\WRO 2017 Maeda\drivers\hitechnic-colour-v1.h"
#include "Sab.h"

void Setup(int m);
void Task_Act(int x);
int BaseVar(int m);
void DeciderVar(int m);
void getTB(void);

int static BC[3]={11,11,11};//Base Color
int static DC[3]={10,5,2};//Decider Color
int static TC[4]={11,11,11,11};
int g[4]={2,4,6,8};
int c[3]={0,0,0};
int static s;

task main(){

int m,n=0,p;
for(m=0;m<4;m++){
	if(colorsound(DC[0])==TC[m]){ c[2]=m; p+=1; }
	if(colorsound(DC[1])==TC[m]){ c[1]=m; p+=10; }
	if(colorsound(DC[2])==TC[m]){ c[0]=m; p+=100; }
}

for(m=0;m<4;m++){
	if(colorsound(DC[0])==TC[m]) c[2]=m;
	if(colorsound(DC[1])==TC[m]) c[1]=m;
	if(colorsound(DC[2])==TC[m]) c[0]=m;
}

void ReadTB(void){
	StopF(-15);
	Arm(U,700,100,F);
	sleep(1000);
	Arm(C,0,-100,F);
	sleep(500);
	ST(17,20);
	for(c=3;c>=0;c--){
		sleep(300);
		if(HTCSreadColor(S1)<11||s_hitec(S1)>200) TC[c]=colorsound(HTCSreadColor(S1));
		else TC[c]=colorsound(HTCSreadColor(S2));
		if(c!=0) ST(10,20);
	}
}

if(p==111||p==110||p==001){ a=1;b=2;t=0; );

if(p==011||p==100||p==101){ a=0;b=1;t=0; );





	//TR(R,50);
	int n=5;
	//	opentest();
	Ready();
	//Arm(U,H2,100,T);
	while(1){
		Task_Act(n);
		n++;
	}
}


void Task_Act(int x){

	if(x!=0) playSoundFile("Activate");

	if(x==0){
		Mode=1;
		ST(20,50);
		Btrace();
		TR(R,70);
		ST(6.5,20);
		TR(R/2,70);
		Mode=0;
	}

	if(x==1){
		playSoundFile("One");
		Setup(0);
		TL(R/2,70);
		while(getColorReflected(S3)>30) Mv(30);
		TL(R,-50);
		playImmediateTone(220,30);
		//RT(R,50);
	}

	if(x==2){
		playSoundFile("Two");
		Setup(1);
		//ST(2,70);
		//Arm(C,0,-100,F);
		//sleep(500);
		while(getColorReflected(S3)>30) Mv(-30);
		ST(17,-70);
		TL(R/2,-70);
		ST(17,-70);
		while(getColorReflected(S4)>30) Mv(-30);
		ST(2,-30);
		TR(R,-50);
		//Arm(C,M,100,T);
		//ST(6,30);
		//Arm(C,0,-100,F);
	}

	if(x==3){
		playSoundFile("Three");
		Setup(2);
		//ST(2,70);
		displayTextLine(1,"DC:%d%d%d",DC[0],DC[1],DC[2]);
		displayTextLine(2,"BC:%d%d%d",BC[0],BC[1],BC[2]);
		//Arm(C,0,-100,F);
		//sleep(500);
		ST(23,-100);
		StopB(-20);
		ST(9.5,-30);
		LT(R,70);
		//Arm(C,M,100,T);
		ST(6,30);
		//Arm(C,0,-100,F);
		FPOWER=20;
		while(getColorReflected(S3)>30) trace();
		ST(5,30);
		playImmediateTone(400,30);
		while(getColorReflected(S3)>30) trace();
		TL(R,-30);
	}
	if(x==4){
		Arm(C,L,100,T);
		getTB();
		ST(2,-30);
		LT(R,30);
		while(getColorReflected(S3)>30) Mv(30);
		ST(3,30);
		StopB(20);
		ST(10,-30);
		Arm(C,S,100,T);
		RT(R,30);
		getTB();
		displayTextLine(5,"TC:%d_%d_%d_%d",TC[0],TC[1],TC[2],TC[3]);
		sleep(1000000000);
	}

	if(x==5){



		int x;
		for(x=0;x<=2;x++){
			playImmediateTone(220,30);
			if(BC[x]>=1&&BC[x]<=3) g[0]=0;
			if(BC[x]==0) g[1]=0;
			if(BC[x]==4) g[2]=0;
			if(BC[x]==5||BC[x]==6) g[3]=0;
		}



				for(x=0;x<=3;x++){
			if(g[x]!=0){
				BF=g[x]-1;
				s=BF;
				if(g[x]>4){
					g[x]=8-g[x];
					LT(g[x]*R/2,30);
				}
				else RT(g[x]*R/2,30);
				break;
			}
		}
	}

}


void Setup(int m){
	Btrace();
	MRST();
	Arm(U,0,-100,F);
	Arm(C,L,100,F);
	ST(2,50);
	TR(R/2,50);
	while(getColorReflected(S4)>20) Mv(30);
	MRST();
	ST(2,30);
	Arm(C,0,-100,F);
	sleep(500);
	/*if(HTCSreadColor(S2)==0||(HTCSreadColor(S2)>11&&s_hitec(S2)<150))*/if(getMotorEncoder(ca)>70) BaseVar(m);
	else  DeciderVar(m);
}


int BaseVar(int m){
	//Arm(C,L,100,T);
	//ST(7,30);
	//Arm(C,0,-100,F);
	//sleep(500);
	Arm(U,50,100,T);
	//if(getMotorEncoder(ca)<70) { ST(5.5,-30); DeciderVar(m); return(1); }
	while(getColorReflected(S4)>20) Mv(-50);
	TR(R+5,-50);
	Arm(C,M,100,F);
	ST(5,30);
	//Arm(C,0,-100,F);
	while(getColorReflected(S3)>20) Mv(50);
	ST(2,20);
	//sleep(300);
	//DC[m]=HTCSreadColor(S2);
	//if(DC[m]>=11&&s_hitec(S2)<30) DC[m]=0;
	//Arm(C,L,100,T);
	Arm(U,0,-100,F);
	sleep(200);
	Arm(C,0,-100,F);
	sleep(300);
	Arm(U,50,100,T);
	ST(12-m*5.5,-30);
	Arm(C,S,30,T);
	Arm(C,M,100,T);
	Arm(U,H2,100,F);
	ST(4,-25);
	Arm(C,0,-100,F);
	sleep(300);
	Arm(U,430,100,T);
	ST(4,25);
	Arm(U,270,-100,T);
	Arm(C,M,50,T);
	Arm(U,420,100,F);
	ST(1.5,-30);
	Arm(C,100,-100,T);
	sleep(200);
	if(HTCSreadColor(S2)<11) BC[m]=HTCSreadColor(S2);
	else BC[m]=HTCSreadColor(S1);
	Arm(C,0,-100,F);
	RT(30,30);
	sleep(500);
	DC[m]=HTCSreadColor(S2);
	displayTextLine(1,"DC:%d%d%d",DC[0],DC[1],DC[2]);
	displayTextLine(2,"BC:%d%d%d",BC[0],BC[1],BC[2]);
	RT(30,-30);
	Arm(C,L,100,T);
	Arm(U,0,-100,F);
	sleep(500);
	while(getColorReflected(S3)>20) Mv(30);
	ST(8,30);
	Arm(C,0,-100,F);
	sleep(300);
	return(1);
}


void DeciderVar(int m){
	//DC[m]=HTCSreadColor(S2);
	//if(DC[m]>=11&&s_hitec(S2)<30) DC[m]=0;
	//Arm(C,L,100,T);
	//ST(2,30);
	//Arm(U,0,-100,F);
	//sleep(300);
	//Arm(C,0,-100,F);
	//sleep(300);
	Arm(U,50,100,T);
	while(getColorReflected(S4)>20) Mv(-50);
	TR(R+5,-50);
	ST(5,30);
	while(getColorReflected(S3)>20) Mv(30);
	MRST();
	Arm(C,S,30,T);
	Arm(C,L,100,F);
	sleep(500);
	Arm(U,H2,100,T);
	ST(8,30);
	Arm(C,0,-100,F);
	sleep(500);
	Arm(U,430,100,T);
	if(m!=2)ST(7.5,-30);
	else ST(5,-30);
	Arm(U,270,-100,T);
	Arm(C,M,50,T);
	Arm(U,420,100,T);
	ST(1.5,-30);
	Arm(C,100,-100,T);
	sleep(200);
	if(HTCSreadColor(S2)<11) BC[m]=HTCSreadColor(S2);
	else BC[m]=HTCSreadColor(S1);
	Arm(C,0,-100,F);
	RT(30,30);
	sleep(500);
	DC[m]=HTCSreadColor(S2);
	displayTextLine(1,"DC:%d%d%d",DC[0],DC[1],DC[2]);
	displayTextLine(2,"BC:%d%d%d",BC[0],BC[1],BC[2]);
	RT(30,-30);
	Arm(C,L,100,T);
	Arm(U,0,-100,F);
	sleep(500);
	ST(8,30);
	Arm(C,0,-100,F);
	sleep(300);
}


void getTB(void){
	int c,d=0,k,a=0;
	int pk[3]={5,5,5};
	StopF(-15);
	Arm(U,700,100,F);
	sleep(1000);
	Arm(C,0,-100,F);
	sleep(500);
	ST(17,20);
	for(c=3;c>=0;c--){
		sleep(300);
		if(HTCSreadColor(S1)<11||s_hitec(S1)>200) TC[c]=colorsound(HTCSreadColor(S1));
		else TC[c]=colorsound(HTCSreadColor(S2));
		if(c!=0) ST(10,20);
	}
	int r=0,b=0;
	for(k=0;k<3;k++){
		for(c=0;c<4;c++){
			if(colorsound(DC[k])==TC[c]){ if(pk[k]!=5) d=c; else pk[k]=c; }
		}
	}
	displayTextLine(2,"pk:%d%d%d",pk[0],pk[1],pk[2]);
	sleep(5000);
	for(k=0;k<3;k++){
		if(pk[k]!=5){
			if(a!=0){
				StopF(-15);
				Arm(U,700,100,F);
				sleep(1000);
				Arm(C,0,-100,F);
				sleep(500);
				ST(47,20);
			}
			ST((pk[k]*10)-2,-20);
			if((TC[pk[k]]==1&&b==0)||(TC[pk[k]]==5&&r==0)){
				Arm(U,300,-100,F);
				sleep(500);
				Arm(U,700,100,F);
				sleep(700);
				if(TC[d]==1) b=1;
				else r=1;
			}
			Arm(C,L,100,T);
			Arm(U,0,-100,F);
			sleep(1000);
			Arm(C,0,-100,F);
			sleep(1000);
			if(getMotorEncoder(ca)<50&&d!=0){
				Arm(U,700,100,F);
				sleep(700);
				ST((d-pk[k])*10-2,-20);
				Arm(C,L,100,T);
				Arm(U,0,-100,F);
				sleep(1000);
				Arm(C,0,-100,F);
				sleep(1000);
				pk[k]=d;
			}
			Arm(U,700,100,F);
			sleep(700);
			pk[k]=(3-pk[k])*10;
			ST(pk[k],-20);
			a=(2-k)*5.6;
			ST(20+a,-20);
			Arm(U,500,-100,T);
			Arm(C,M,100,T);
			pk[k]=0;
			Arm(C,L,100,T);
			ST(6+a,20);
			Arm(U,H2,-100,T);
			if(k==2) ST(3,20);
			Arm(U,0,-100,F);
			sleep(1000);
		}
		displayTextLine(2,"pk:%d%d%d",pk[0],pk[1],pk[2]);
	}
	Arm(C,0,-100,F);
	sleep(500);
}

/*


				Arm(U,300,100,T);
		while(0>HTCSreadColor(S1)||HTCSreadColor(S1)>11) trace();
		MRST();
		Arm(C,L,100,T);
		Arm(U,300,100,T);
		ST(7,-20);
		Arm(C,0,-100,F);
		sleep(700);
		ST(15,20);
		Arm(U,700,100,F);
		sleep(1000);
		ST(6,-20);
		Arm(U,250,-100,T);
		Arm(C,L,100,T);
		Arm(U,600,100,T);
		ST(11,20);
		Arm(U,0,-100,F);
		sleep(700);
		Arm(C,M,-100,F);
		sleep(500);
		Arm(U,H5,100,T);
		ST(11,-20);
		Arm(C,L,100,T);

*/
