#pragma config(Sensor, S1,     Lsensor,        sensorI2CCustom)
#pragma config(Sensor, S2,     Rsensor,        sensorI2CCustom)
#pragma config(Sensor, S3,		 TIR,						 sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          Lmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Rmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          arm2,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers\hitechnic-colour-v1.h"
#include "drivers/ultrasonic_UMX.h"
#include "drivers\S_UMX.h"
#include "test_sub.h"

#define smux_port S3
#define smux_address 0x08


task main()
{
	setup_ultrasonic_mux(S3,0X04,3);
	setup_smux(smux_port,smux_address);
	led_con(LED_on);
	TYjudge(1,2,'Y');
	opentest(0);
	while(1){
		map();
		//trace();
		//kousaten();
	}
}
