#pragma config(Sensor, S1,     Lsensor,        sensorI2CCustom)
#pragma config(Sensor, S2,     Rsensor,        sensorI2CCustom)
#pragma config(Motor,  motorA,          Lmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Rmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          arm2,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers\hitechnic-colour-v1.h"
#include "drivers\S_UMX.h"
#include "test_sub.h"

task main()
{
	setup_smux(smux_port,smux_address);
	led_con(LED_on);
	while(1){
		trace();
		kousaten();
	}
}
