#pragma config(Sensor, S1,     Lsensor,        sensorI2CCustom)
#pragma config(Sensor, S2,     Rsensor,        sensorI2CCustom)
#pragma config(Sensor, S3,		 TIR,						 sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          Lmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Rmotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          arm2,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers\hitechnic-colour-v1.h"
#include "drivers/ultrasonic_UMX.h"
#include "drivers\S_UMX.h"
#include "test_sub.h"



void test(void);

void moveArm(int x){
	RST();
	if(x==0){
		moveMotorTarget(motorC,50,50); moveMotorTarget(motorD,50,50); sleep(500);
		mv(250,-70);
		moveMotorTarget(motorC,150,30); moveMotorTarget(motorD,150,30); sleep(1000); }
	if(x==1){
		mv(300,70); mv(300,-70);
		moveMotorTarget(motorC,50,-50); moveMotorTarget(motorD,50,-50); sleep(500);
		moveMotorTarget(motorC,150,-50); moveMotorTarget(motorD,150,-50); sleep(1000); }
}

task main()
{
	int cou=0;
	setup_ultrasonic_mux(S3,0X04,3);
	setup_smux(smux_port,smux_address);
	led_con(LED_on);
	while(1){
		if(digital_read(D8)==1)	{ motor[Lmotor]=55; motor[Rmotor]=60;	}
		else										{ motor[Lmotor]=60; motor[Rmotor]=57;	}
		if(analog_read(A3)!=0){cou++;sleep(10);if(cou>3){moveArm(0);moveArm(1);}}
		else cou=0;
		if(digital_read(D1)||digital_read(D2)){
			mv(50,50);
			if(digital_read(D1)&&digital_read(D2)){ moveArm(0); Bturn(300,-70);Bturn(300,70); mv(350,70); turn(700,-70); moveArm(1);}
			else {playImmediateTone(600,30); opentest();}
		}
	}
	opentest();
	while(1){
		//test();
		trace();
		kousaten();
		syougai();
	}
	/*

	*/
}



void test(void){

}
